KhumaloCraft/Models/ProductInformation.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KhumaloCraft.Models
{
    public class ProductInformation
    {
        [Key]
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        [Required]
        public double ProductPrice { get; set; }
        [Required]
        public string ProductCategory { get; set; }
        [Required]
        public Boolean ProductAvailability { get; set; }
        public string UserID { get; set; }

        [ForeignKey("UserID")]
        public IdentityUser User { get; set; }

        public ProductInformation()
        {

        }
    }
}

KhumaloCraft/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KhumaloCraft.Data;
using KhumaloCraft.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;

namespace KhumaloCraft.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CartsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Carts
        [Authorize(Roles = "Consumer")]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var cart = await _context.Cart.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefaultAsync(c => c.UserID == user.Id && !c.OrderConfirmed);

            return View(cart);
        }

        // POST: AddToCart
        [Authorize(Roles = "Consumer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart([FromForm] int ProductId, [FromForm] bool Available, int quantity = 1)
        {
            var user = await _userManager.GetUserAsync(User);
            var cart = await _context.Cart.Include(c => c.CartItems).FirstOrDefaultAsync(c => c.UserID == user.Id && !c.OrderConfirmed);

            if (cart == null)
            {
                cart = new Cart { UserID = user.Id, OrderConfirmed = false };
                _context.Cart.Add(cart);
                await _context.SaveChangesAsync();
            }

            if (ProductId == 0)
            {
                return NotFound();
            }

            if (!Available)
            {
                return Content("<script>alert('The product is not available.'); window.location.href = '/ProductInformations/Index';</script>", "text/html");
            }

            var cartItem = cart.CartItems.FirstOrDefault(ci => ci.ProductID == ProductId);

            if (cartItem == null)
            {
                cartItem = new CartItem { ProductID = ProductId, Quantity = quantity };
                cart.CartItems.Add(cartItem);
            }
            else
            {
                cartItem.Quantity += quantity;
            }

            await _context.SaveChangesAsync();
            TempData["ItemAddedToCart"] = true;
            return RedirectToAction("Index", "ProductInformations");
        }

        // POST: Checkout
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout()
        {
            var user = await _userManager.GetUserAsync(User);
            var cart = await _context.Cart.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefaultAsync(c => c.UserID == user.Id && !c.OrderConfirmed);

            if (cart == null || !cart.CartItems.Any())
            {
                return Content("<script>alert('There are no items in the cart'); window.location.href = '/Carts/Index';</script>", "text/html");
            }
            else
            {
                cart.OrderConfirmed = true;
                cart.OrderDate = DateTime.UtcNow;
                await _context.SaveChangesAsync();

                TempData["Checkout"] = true;

                return RedirectToAction(nameof(OrderHistory));
            }
        }

        // POST: ClearCart
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearCart()
        {
            var user = await _userManager.GetUserAsync(User);
            var cart = await _context.Cart.Include(c => c.CartItems).FirstOrDefaultAsync(c => c.UserID == user.Id && !c.OrderConfirmed);

            if (cart != null)
            {
                _context.RemoveRange(cart.CartItems);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        // GET: OrderHistory
        public async Task<IActionResult> OrderHistory()
        {
            var user = await _userManager.GetUserAsync(User);
            var orders = await _context.Cart.Include(c => c.CartItems).ThenInclude(ci => ci.Product).Where(c => c.UserID == user.Id && c.OrderConfirmed).ToListAsync();

            return View(orders);
        }

        // POST: ClearOrders
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearOrders()
        {
            var user = await _userManager.GetUserAsync(User);
            var orders = await _context.Cart.Include(c => c.CartItems).ThenInclude(ci => ci.Product).Where(c => c.UserID == user.Id && c.OrderConfirmed).ToListAsync();

            if (orders != null)
            {
                _context.RemoveRange(orders);
                await _context.SaveChangesAsync();
            }
            return View(orders);
        }
    }
}

KhumaloCraft/Controllers/ProductInformationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KhumaloCraft.Data;
using KhumaloCraft.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Azure.Search.Documents.Indexes;
using Azure.Search.Documents;
using Azure;
using System.Diagnostics;

namespace KhumaloCraft.Controllers
{
    public class ProductInformationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ProductInformationsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ProductInformations
        public async Task<IActionResult> Index()
        {

            if (User.IsInRole("Merchant"))
            {
                var user = _userManager.GetUserId(User);
                var items = await _context.ProductInformation.Where(i => i.UserID == user).ToListAsync();

                return View(items);
            }
            else
            {
                var items = await _context.ProductInformation.ToListAsync();
                return View(items);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Index(SearchData model)
        {
            try
            {
                // Check for a search string
                if (model.searchText == null)
                {
                    model.searchText = "";
                }

                await RunQueryAsync(model);
            }

            catch
            {
                return View("Error", new ErrorViewModel { RequestId = "1" });
            }
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private static SearchClient _searchClient;
        private static SearchIndexClient _indexClient;
        private static IConfigurationBuilder _builder;
        private static IConfigurationRoot _configuration;

        private void InitSearch()
        {
            // Create a configuration using appsettings.json
            _builder = new ConfigurationBuilder().AddJsonFile("appsettings.json");
            _configuration = _builder.Build();

            // Read the values from appsettings.json
            string searchServiceUri = _configuration["SearchServiceUri"];
            string queryApiKey = _configuration["SearchServiceQueryApiKey"];

            // Create a service and index client.
            _indexClient = new SearchIndexClient(new Uri(searchServiceUri), new AzureKeyCredential(queryApiKey));
            _searchClient = _indexClient.GetSearchClient("hotels-sample-index");
        }

        private async Task<ActionResult> RunQueryAsync(SearchData model)
        {
            InitSearch();

            var options = new SearchOptions()
            {
                IncludeTotalCount = true
            };

            // Enter 'property names' to specify which fields are returned.
            // If Select is empty, all "retrievable" fields are returned.
            options.Select.Add("ProductName");
            options.Select.Add("ProductPrice");
            options.Select.Add("ProductCategory");
            options.Select.Add("ProductAvailability");

            // For efficiency, the search call should be asynchronous, so use SearchAsync rather than Search.
            model.resultList = await _searchClient.SearchAsync<ProductInformation>(model.searchText, options).ConfigureAwait(false);

            return View("Index", model);
        }

        // GET: Pottery
        public async Task<IActionResult> ShowPottery()
        {
            return View("Index", await _context.ProductInformation.Where(i => i.ProductCategory.Contains("Pottery")).ToListAsync());
        }

        // GET: Crochet
        public async Task<IActionResult> ShowCrochet()
        {
            return View("Index", await _context.ProductInformation.Where(i => i.ProductCategory.Contains("Crochet")).ToListAsync());
        }

        // GET: Lapidary
        public async Task<IActionResult> ShowLapidary()
        {
            return View("Index", await _context.ProductInformation.Where(i => i.ProductCategory.Contains("Lapidary")).ToListAsync());
        }

        // GET: MetalWork
        public async Task<IActionResult> ShowMetalWork()
        {
            return View("Index", await _context.ProductInformation.Where(i => i.ProductCategory.Contains("MetalWork")).ToListAsync());
        }

        // GET: ProductInformations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productInformation = await _context.ProductInformation
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (productInformation == null)
            {
                return NotFound();
            }

            return View(productInformation);
        }

        // GET: ProductInformations/Create
        [Authorize(Roles = "Merchant")]
        public IActionResult Create()
        {
            List<string> category = new List<string>()
            {
                "Pottery", "Crochet", "Lapidary", "MetalWork"
            };

            ViewBag.Category = new SelectList(category);

            return View();
        }

        // POST: ProductInformations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Merchant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,ProductName,ProductPrice,ProductCategory,ProductAvailability")] ProductInformation productInformation)
        {
                var user =  await _userManager.GetUserAsync(User);
                productInformation.UserID = user.Id;

                _context.Add(productInformation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
        }

        // GET: ProductInformations/Edit/5
        [Authorize(Roles = "Merchant")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productInformation = await _context.ProductInformation.FindAsync(id);
            if (productInformation == null)
            {
                return NotFound();
            }
            return View(productInformation);
        }

        // POST: ProductInformations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Merchant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,ProductName,ProductPrice,ProductCategory,ProductAvailability")] ProductInformation productInformation)
        {
            var user = await _userManager.GetUserAsync(User);
            productInformation.UserID = user.Id;

            if (id != productInformation.ProductID)
            {
                return NotFound();
            }

            try
            {
                _context.Update(productInformation);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductInformationExists(productInformation.ProductID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: ProductInformations/Delete/5
        [Authorize(Roles = "Merchant")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productInformation = await _context.ProductInformation
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (productInformation == null)
            {
                return NotFound();
            }

            return View(productInformation);
        }

        // POST: ProductInformations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productInformation = await _context.ProductInformation.FindAsync(id);
            if (productInformation != null)
            {
                _context.ProductInformation.Remove(productInformation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductInformationExists(int id)
        {
            return _context.ProductInformation.Any(e => e.ProductID == id);
        }
    }
}

KhumaloCraft/Views/ProductInformations/Create.cshtml
@model KhumaloCraft.Models.ProductInformation

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProductInformation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" onsubmit="return validateForm()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" required type="number" min="1" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCategory" class="control-label"></label>
                @Html.DropDownListFor(model => model.ProductCategory, (SelectList)ViewBag.Category, "Select Category", new {@class="form-control"})
                <span asp-validation-for="ProductCategory" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                <input class="form-check-input" asp-for="ProductAvailability" /> @Html.DisplayNameFor(model => model.ProductAvailability)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-sm btn-primary" /> |
                <a asp-action="Index" class="btn btn-sm btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function validateForm() 
        {
            var isValid = true;
            var inputs = document.querySelectorAll('input[required], select[required]');
            inputs.forEach(function (input) 
            {
                if (!input.value) 
                {
                    isValid = false;
                    input.classList.add('is-invalid');
                }
                else 
                {
                    input.classList.remove('is-invalid');
                }
            });
            return isValid;
        }
    </script>
}

KhumaloCraft/Views/ProductInformations/Delete.cshtml
@model KhumaloCraft.Models.ProductInformation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductInformation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductAvailability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductAvailability)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductID" />
        <input type="submit" value="Delete" class="btn btn-sm btn-danger" /> |
        <a asp-action="Index" class="btn btn-sm btn-primary">Back to List</a>
    </form>
</div>

KhumaloCraft/Views/ProductInformations/Details.cshtml
@model KhumaloCraft.Models.ProductInformation

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProductInformation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductAvailability)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductAvailability)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ProductID" class="btn btn-sm btn-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-sm btn-primary">Back to List</a>
</div>

KhumaloCraft/Views/ProductInformations/Edit.cshtml
@model KhumaloCraft.Models.ProductInformation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProductInformation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductID" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCategory" class="control-label"></label>
                <input asp-for="ProductCategory" class="form-control" />
                <span asp-validation-for="ProductCategory" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ProductAvailability" /> @Html.DisplayNameFor(model => model.ProductAvailability)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-sm btn-primary" /> |
                <a asp-action="Index" class="btn btn-sm btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

KhumaloCraft/Views/ProductInformations/Index.cshtml
@model IEnumerable<KhumaloCraft.Models.ProductInformation>

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Product Information";
}

<h1>Product Information</h1>

<p>
    @if (User.IsInRole("Merchant"))
    {
        <a asp-action="Create" class="btn btn-sm btn-primary">Create New</a>
    }
</p>

@if (Model != null && Model.Any())
{
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductAvailability)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCategory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductAvailability)
            </td>
                @if (User.IsInRole("Merchant"))
                {
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ProductID" class="btn btn-sm btn-warning">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ProductID" class="btn btn-sm btn-info">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ProductID" class="btn btn-sm btn-danger">Delete</a>
                    </td>
                }
                else if (User.IsInRole("Consumer"))
                {
                    <td>
                        <form asp-controller="Carts" asp-action="AddToCart" method="post">
                            <input type="hidden" name="ProductId" value="@item.ProductID"/>
                            <input type="hidden" name="Available" value="@(item.ProductAvailability ? "true" : "false")"/>
                            <button type="submit" class="btn btn-sm btn-primary">Add to Cart</button>
                        </form>
                    </td>
                }
                else
                {
                    <td>
                        <a class="btn btn-sm btn-primary" onclick="alert('You need to be logged in to add items to the cart.')">Add to Cart</a>
                    </td>
                }
        </tr>
}
    </tbody>
</table>

    @if (TempData["ItemAddedToCart"] != null && (bool)TempData["ItemAddedToCart"])
    {
        <script>
            alert("Item added to cart successfully!");
        </script>
    }
}
else
{
    <p>No products available.</p>
}